profiles:
    active=@spring.profile.from.maven@
debug:
    true
logging:
    level:
        org:
            hibernate:
                SQL: debug

spring:
    datasource:
        url: jdbc:mariadb://127.0.0.1:3306/cdbb?allowMultiQueries=true
        username: cdbb
        password: cdbbpw
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto:create
        show-sql: true
        properties.hibernate.enable_lazy_load_no_trans: true
    sql:
        init:
            mode=never:

    liquibase:
        change-log: 'classpath:database/liquibase-changelog-main.yaml'
    web.cors.allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:4200"
    security.user.password: "TJuw3udSWLbHBRc"

---
spring:
    profiles: azure-active-directory
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: https://login.microsoftonline.com/a76f7f54-71f8-4ab4-8cb5-a1a21a6b5d26/discovery/v2.0/keys
                    issuer-uri: https://login.microsoftonline.com/{a76f7f54-71f8-4ab4-8cb5-a1a21a6b5d26}/v2.0

    #cloud:
     #   azure:
      #      active-directory:
       #         enabled: true
        #        profile:
         #           tenant-id: a76f7f54-71f8-4ab4-8cb5-a1a21a6b5d26
          #      credential:
           #         client-id: 12238474-6457-44c0-8485-ab57ae490c98
            #        client-secret: 1b9a2b19-57d8-4060-81aa-40fc13ef5d50


management:
    endpoint.health.show-details: always
    endpoints.web.exposure.include:
        - health
        - httptrace
        - info
        - integrationgraph
        - liquibase
        - mappings



