
logging:
    level:
        org:
            hibernate:
                SQL: debug

spring:
    datasource:
        url: jdbc:mariadb://127.0.0.1:3306/cdbb?allowMultiQueries=true
        username: cdbb
        password: cdbbpw
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto:create
        show-sql: true
        properties.hibernate.enable_lazy_load_no_trans: true
    sql:
        init:
            mode=never:

    liquibase:
        change-log: 'classpath:database/liquibase-changelog.yaml'
    web.cors.allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:4200"
    security.user.password: "TJuw3udSWLbHBRc"
management:
    endpoint.health.show-details: always
    endpoints.web.exposure.include:
        - health
        - httptrace
        - info
        - integrationgraph
        - liquibase
        - mappings
