
logging:
    level:
        org:
            hibernate:
                SQL: debug

spring:
    jpa:
        show-sql: true
        properties.hibernate.enable_lazy_load_no_trans: true
    h2:
        console:
            enabled: true
    liquibase:
        change-log: 'classpath:database/liquibase-changelog.yaml'
    web.cors.allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:4200"
    security.user.password: "TJuw3udSWLbHBRc"
management:
    endpoint.health.show-details: always
    endpoints.web.exposure.include:
        - health
        - httptrace
        - info
        - integrationgraph
        - liquibase
        - mappings
