trigger:
  branches:
    include:
      - feature/cdbb-151-UsersAndPermissions
      - feature/cdbb-152-ImportAndExport
      - feature/cdbb-153-Final-drop-without-showcase-functionality
      - feature/cdbb-154_Showcase_Version
  paths:
    include:
      - frontend/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: dir
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: cd

- script: |
    npm install -g @angular/cli
    npm install --legacy-peer-deps
    ng build --configuration=offline
  workingDirectory: 'frontend'
  displayName: 'npm install and build'

- script: |
    ng test --watch=false --code-coverage --karma-config=karma-devops.conf.js
  continueOnError: true
  workingDirectory: 'frontend'
  displayName: 'karma tests'

- task: PublishPipelineArtifact@0
  inputs:
    targetPath: $(Build.SourcesDirectory)/frontend/dist
    artifact: 'drop'
    publishLocation: 'pipeline'
  displayName: 'Store artifact'