trigger:
  branches:
    include:
      - feature/cdbb-151-UsersAndPermissions
      - feature/cdbb-152-ImportAndExport
  paths:
    include:
      - frontend/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: dir
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: cd

- script: |
    npm install -g @angular/cli
    npm install --legacy-peer-deps
    ng build
  workingDirectory: 'frontend'
  displayName: 'npm install and build'

- script: |
    ng test --watch=false --code-coverage --karma-config=karma-devops.conf.js
  continueOnError: true
  workingDirectory: 'frontend'
  displayName: 'karma tests'

#- task: CopyFiles@2
#  inputs:
#    SourceFolder: '$(Build.SourcesDirectory)/AdminPortal/dist'
#    targetFolder: '$(Build.ArtifactStagingDirectory)'

#- task: PublishBuildArtifacts@1
#  displayName: 'Publish Artifact: drop'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'