export enum DashboardDialog {
    NONE,
    NEW_PROJECT_DIALOG = 1,
    DELETE_PROJECT_DIALOG = 2,
    COPY_PROJECT_DIALOG = 3,
    RENAME_PROJECT_DIALOG = 4,
    IMPORT_PROJECT_DIALOG = 5,
    IMPORT_FOD_DIALOG = 6,
    IMPORT_DICTIONARY_DIALOG = 7
}
